 
#The aim of this script is to clean the pitch files generated by praat

#find /home/user/pra/pit/ -type f -exec sed -i "s|--undefined--|0|g" 

find /home/user/pra/pit/ -type f -name "*.Pitch" -print0 | xargs -0 sed -i "s/--undefined--/0/g"
